import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | Advanta AI",
  description: "Terms and conditions for using Advanta AI's tools, workflows, and services.",
};

export default function TermsPage() {
  const sections = [
    {
      title: "Acceptance of Terms",
      body: `By accessing or using Advanta AI's website, free tools, or purchasing any workflow or service, you agree to be bound by these Terms of Service. If you do not agree, please do not use our services.`,
    },
    {
      title: "Free AI Tools",
      body: `Our free AI tools are provided as-is for informational and productivity purposes. The outputs generated by our tools are AI-generated and should be reviewed before use. We do not guarantee the accuracy, completeness, or fitness for any particular purpose of AI-generated content. You are responsible for reviewing and editing any output before relying on it.`,
    },
    {
      title: "Workflow Purchases",
      body: `Upon purchasing a workflow, you receive a non-exclusive, non-transferable license to use the workflow templates, blueprints, and materials for your own business. You may not resell, redistribute, or sublicense the workflow materials to third parties. All purchases are subject to our 30-day money-back guarantee as described at the time of purchase.`,
    },
    {
      title: "Prohibited Uses",
      body: `You may not use our services to generate spam, misinformation, illegal content, content that infringes intellectual property rights, or content that violates any applicable law. We reserve the right to terminate access for any user we determine to be in violation of these terms.`,
    },
    {
      title: "Intellectual Property",
      body: `The Advanta AI brand, website design, and proprietary systems are owned by Advanta AI. AI-generated content produced through our tools is yours to use subject to OpenAI's usage policies. Workflow blueprints and templates remain licensed to you (not transferred in ownership) under these terms.`,
    },
    {
      title: "Limitation of Liability",
      body: `To the maximum extent permitted by law, Advanta AI shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of our services or any AI-generated content. Our total liability shall not exceed the amount you paid to us in the 12 months prior to the claim.`,
    },
    {
      title: "Refund Policy",
      body: `Workflow purchases include a 30-day money-back guarantee. If the workflow does not work for your setup or you are unsatisfied, email hello@advanta-ai.com within 30 days of purchase for a full refund. No questions asked.`,
    },
    {
      title: "Changes to Terms",
      body: `We may update these terms from time to time. Continued use of our services after any update constitutes acceptance of the new terms. We will notify users of material changes via email where possible.`,
    },
    {
      title: "Contact",
      body: `Questions about these Terms? Contact us at hello@advanta-ai.com.`,
    },
  ];

  return (
    <div className="min-h-screen bg-white">
      <Header />
      <main className="pt-24 pb-20">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="mb-10">
            <h1 className="text-4xl font-bold text-gray-900 mb-3">Terms of Service</h1>
            <p className="text-gray-500">Last updated: June 2026</p>
          </div>
          <p className="text-gray-600 leading-relaxed mb-10">
            These Terms of Service govern your use of Advanta AI's website, free tools, and paid workflow products. Please read them carefully.
          </p>
          <div className="space-y-8">
            {sections.map((s, i) => (
              <div key={i}>
                <h2 className="text-xl font-bold text-gray-900 mb-3">{s.title}</h2>
                <p className="text-gray-600 leading-relaxed">{s.body}</p>
              </div>
            ))}
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
