export interface Agent {
  id: string;
  name: string;
  tagline: string;
  description: string;
  icon: string; // emoji
  category: string;
  price: number;
  priceNote: string;
  pricingModel: "monthly" | "per-user" | "usage";
  rating: number;
  reviews: number;
  deployTime: string;
  tags: string[];
  features: string[];
  integrations: string[];
  metrics: { label: string; value: string }[];
  color: string;
  gradient: string;
  popular?: boolean;
  new?: boolean;
  enterprise?: boolean;
  testimonial?: { quote: string; author: string; company: string };
}

export const agents: Agent[] = [
  {
    id: "sales-ai",
    name: "Sales AI Agent",
    tagline: "Close more deals on autopilot",
    description: "Fully autonomous sales agent that qualifies leads, sends personalized follow-up sequences, updates your CRM, and books meetings — 24/7.",
    icon: "📈",
    category: "Sales",
    price: 297,
    priceNote: "/month",
    pricingModel: "monthly",
    rating: 4.9,
    reviews: 128,
    deployTime: "3 days",
    tags: ["Lead Gen", "CRM", "Email", "Outbound"],
    features: [
      "Automated lead scoring & qualification",
      "Personalized multi-step email sequences",
      "CRM sync (HubSpot, Salesforce, Pipedrive)",
      "AI-powered meeting scheduling",
      "Real-time pipeline reporting",
      "A/B testing for outreach messages",
      "LinkedIn outreach automation",
      "Hot lead alerts via Slack/email",
    ],
    integrations: ["HubSpot", "Salesforce", "Slack", "Gmail", "Calendly", "LinkedIn"],
    metrics: [{ label: "Avg leads increase", value: "+342%" }, { label: "Time saved", value: "15h/week" }, { label: "Reply rate", value: "31%" }],
    color: "blue",
    gradient: "from-blue-500 to-blue-700",
    popular: true,
    testimonial: { quote: "Booked 47 qualified demos in the first month. Game changer.", author: "Marcus T.", company: "SaaS startup, $2M ARR" },
  },
  {
    id: "support-ai",
    name: "Customer Support AI",
    tagline: "Handle 80% of tickets instantly",
    description: "Always-on support agent that understands your products, resolves issues, and escalates complex cases — making your team 10x more efficient.",
    icon: "🎧",
    category: "Support",
    price: 197,
    priceNote: "/month",
    pricingModel: "monthly",
    rating: 4.8,
    reviews: 95,
    deployTime: "2 days",
    tags: ["Helpdesk", "Chatbot", "Tickets", "Live Chat"],
    features: [
      "Natural language understanding",
      "Custom knowledge base training",
      "Intelligent ticket routing",
      "Sentiment analysis & escalation",
      "Multi-channel support (chat, email, SMS)",
      "CSAT scoring automation",
      "Response time SLA monitoring",
      "Multi-language support (40+ languages)",
    ],
    integrations: ["Zendesk", "Intercom", "Freshdesk", "Slack", "Shopify", "Stripe"],
    metrics: [{ label: "Tickets auto-resolved", value: "80%" }, { label: "Response time", value: "<2 min" }, { label: "CSAT improvement", value: "+28%" }],
    color: "green",
    gradient: "from-green-500 to-emerald-600",
    testimonial: { quote: "Cut support costs by 60% while our customer satisfaction went up.", author: "Priya K.", company: "E-commerce, 50K customers" },
  },
  {
    id: "marketing-ai",
    name: "Marketing Automation AI",
    tagline: "Launch campaigns while you sleep",
    description: "Intelligent marketing agent that generates copy, schedules across platforms, A/B tests campaigns, and optimizes ad spend in real-time.",
    icon: "📣",
    category: "Marketing",
    price: 247,
    priceNote: "/month",
    pricingModel: "monthly",
    rating: 4.7,
    reviews: 82,
    deployTime: "3 days",
    tags: ["Content", "Social Media", "Ads", "Email"],
    features: [
      "AI content generation for all platforms",
      "Automated scheduling & publishing",
      "A/B testing with auto-optimization",
      "Ad spend optimization (Google, Meta)",
      "SEO content suggestions",
      "Competitor monitoring & alerts",
      "Performance analytics dashboard",
      "Brand voice consistency engine",
    ],
    integrations: ["Meta Ads", "Google Ads", "Mailchimp", "Buffer", "Canva", "WordPress"],
    metrics: [{ label: "Content output", value: "10x faster" }, { label: "Ad ROAS", value: "+89%" }, { label: "Engagement", value: "+3.2x" }],
    color: "purple",
    gradient: "from-purple-500 to-violet-600",
    new: true,
    testimonial: { quote: "Our social engagement tripled and we're spending 90% less time on content.", author: "Jordan M.", company: "DTC Brand, $5M revenue" },
  },
  {
    id: "ops-ai",
    name: "Operations Workflow AI",
    tagline: "Automate your entire back-office",
    description: "Streamlines operations with intelligent document processing, approvals, data extraction, and cross-system integrations — no more manual work.",
    icon: "⚙️",
    category: "Operations",
    price: 347,
    priceNote: "/month",
    pricingModel: "monthly",
    rating: 4.9,
    reviews: 61,
    deployTime: "5 days",
    tags: ["Automation", "Workflows", "Documents", "Integration"],
    features: [
      "Intelligent document processing (PDF, Word, Excel)",
      "Multi-step approval workflows",
      "Data extraction & transformation",
      "Cross-system API integrations",
      "Automated reporting & alerts",
      "Compliance tracking & audit logs",
      "Error detection & self-healing",
      "Custom workflow builder",
    ],
    integrations: ["Zapier", "Make.com", "Notion", "Airtable", "Google Workspace", "Microsoft 365"],
    metrics: [{ label: "Manual tasks eliminated", value: "94%" }, { label: "Processing time", value: "-87%" }, { label: "Error rate", value: "-99%" }],
    color: "orange",
    gradient: "from-orange-500 to-amber-600",
    enterprise: true,
  },
  {
    id: "analytics-ai",
    name: "Business Intelligence AI",
    tagline: "Ask your data anything",
    description: "Natural language analytics that turns raw data into executive-ready insights, automated reports, and predictive forecasts.",
    icon: "📊",
    category: "Analytics",
    price: 197,
    priceNote: "/month",
    pricingModel: "monthly",
    rating: 4.6,
    reviews: 74,
    deployTime: "2 days",
    tags: ["Data", "Reporting", "BI", "Forecasting"],
    features: [
      "Natural language data queries",
      "Auto-generated weekly/monthly reports",
      "Anomaly detection & alerts",
      "Predictive revenue forecasting",
      "Custom KPI dashboard builder",
      "Data source connections (50+)",
      "Shareable insight snapshots",
      "Executive summary auto-generation",
    ],
    integrations: ["Google Analytics", "Stripe", "Shopify", "PostgreSQL", "BigQuery", "Looker"],
    metrics: [{ label: "Report time saved", value: "8h/week" }, { label: "Forecast accuracy", value: "94%" }, { label: "Data sources", value: "50+" }],
    color: "indigo",
    gradient: "from-indigo-500 to-blue-600",
  },
  {
    id: "hr-ai",
    name: "HR & Recruiting AI",
    tagline: "Hire A-players twice as fast",
    description: "End-to-end recruiting automation — screens resumes, scores candidates, schedules interviews, and delivers onboarding sequences on autopilot.",
    icon: "👥",
    category: "HR",
    price: 227,
    priceNote: "/month",
    pricingModel: "monthly",
    rating: 4.7,
    reviews: 53,
    deployTime: "3 days",
    tags: ["Recruiting", "Onboarding", "HR", "Screening"],
    features: [
      "AI resume screening & scoring",
      "Bias-free candidate ranking",
      "Automated interview scheduling",
      "Personalized onboarding workflows",
      "Employee handbook chatbot",
      "Compliance documentation",
      "Performance review automation",
      "Retention risk detection",
    ],
    integrations: ["Greenhouse", "Lever", "BambooHR", "LinkedIn", "Slack", "DocuSign"],
    metrics: [{ label: "Time-to-hire", value: "-52%" }, { label: "Screening time", value: "-90%" }, { label: "Offer acceptance", value: "+38%" }],
    color: "pink",
    gradient: "from-pink-500 to-rose-600",
  },
  {
    id: "ecommerce-ai",
    name: "E-Commerce Revenue AI",
    tagline: "Increase revenue without more traffic",
    description: "Drives more sales with personalized recommendations, abandoned cart recovery, dynamic pricing, and customer segmentation — all automated.",
    icon: "🛒",
    category: "E-Commerce",
    price: 297,
    priceNote: "/month",
    pricingModel: "monthly",
    rating: 4.8,
    reviews: 89,
    deployTime: "2 days",
    tags: ["Shopify", "Revenue", "Personalization", "Recovery"],
    features: [
      "AI product recommendations engine",
      "Abandoned cart recovery sequences",
      "Dynamic pricing optimization",
      "Customer lifetime value prediction",
      "Upsell & cross-sell automation",
      "Inventory replenishment alerts",
      "Loyalty program automation",
      "Review request sequences",
    ],
    integrations: ["Shopify", "WooCommerce", "Klaviyo", "Meta Ads", "Google Shopping", "Stripe"],
    metrics: [{ label: "Average order value", value: "+34%" }, { label: "Cart recovery rate", value: "28%" }, { label: "LTV increase", value: "+67%" }],
    color: "teal",
    gradient: "from-teal-500 to-cyan-600",
    popular: true,
    testimonial: { quote: "Added $180K in recovered revenue in 90 days. Best ROI we've ever seen.", author: "Sofia R.", company: "Fashion DTC, $3M/year" },
  },
  {
    id: "website-ai",
    name: "Website Conversion AI",
    tagline: "Turn visitors into customers 24/7",
    description: "Smart AI assistant embedded on your website that answers questions, qualifies leads, books demos, and nurtures visitors into customers.",
    icon: "🌐",
    category: "Website",
    price: 97,
    priceNote: "/month",
    pricingModel: "monthly",
    rating: 4.8,
    reviews: 143,
    deployTime: "1 day",
    tags: ["Chatbot", "Lead Gen", "Conversion", "Website"],
    features: [
      "1-line embed on any website",
      "Custom training on your content",
      "Lead capture & qualification",
      "Meeting booking integration",
      "CRM data sync",
      "Analytics & conversation insights",
      "Custom branding & persona",
      "Multi-language support",
    ],
    integrations: ["HubSpot", "Calendly", "Zapier", "Slack", "WordPress", "Webflow"],
    metrics: [{ label: "Lead capture rate", value: "+185%" }, { label: "Response accuracy", value: "97%" }, { label: "Setup time", value: "< 1 day" }],
    color: "cyan",
    gradient: "from-cyan-500 to-blue-500",
    popular: true,
  },
  {
    id: "finance-ai",
    name: "Finance & Accounting AI",
    tagline: "Close the books 5x faster",
    description: "Automates bookkeeping, expense categorization, invoice processing, financial reporting, and cash flow forecasting — your AI CFO.",
    icon: "💰",
    category: "Finance",
    price: 397,
    priceNote: "/month",
    pricingModel: "monthly",
    rating: 4.7,
    reviews: 41,
    deployTime: "5 days",
    tags: ["Bookkeeping", "Invoicing", "CFO", "Forecasting"],
    features: [
      "Automated expense categorization",
      "Invoice processing & matching",
      "Real-time P&L dashboards",
      "Cash flow forecasting (90-day)",
      "Bank reconciliation automation",
      "Tax preparation data export",
      "Vendor payment scheduling",
      "Budget vs actuals tracking",
    ],
    integrations: ["QuickBooks", "Xero", "Stripe", "Bill.com", "Plaid", "Google Sheets"],
    metrics: [{ label: "Accounting time", value: "-75%" }, { label: "Invoice processing", value: "< 30 sec" }, { label: "Forecast accuracy", value: "96%" }],
    color: "yellow",
    gradient: "from-yellow-500 to-orange-500",
    enterprise: true,
  },
  {
    id: "legal-ai",
    name: "Legal Document AI",
    tagline: "Contracts reviewed in minutes, not days",
    description: "Reviews contracts, flags risky clauses, generates standard legal documents, and monitors compliance — at a fraction of lawyer costs.",
    icon: "⚖️",
    category: "Legal",
    price: 447,
    priceNote: "/month",
    pricingModel: "monthly",
    rating: 4.6,
    reviews: 38,
    deployTime: "3 days",
    tags: ["Contracts", "Compliance", "NDA", "Legal"],
    features: [
      "Contract review & risk flagging",
      "NDA & agreement generation",
      "Compliance monitoring & alerts",
      "Clause library & templates",
      "Redline & negotiation suggestions",
      "E-signature workflow integration",
      "Regulatory update tracking",
      "Legal Q&A chatbot",
    ],
    integrations: ["DocuSign", "PandaDoc", "Notion", "Slack", "Google Drive", "Dropbox"],
    metrics: [{ label: "Review time", value: "-90%" }, { label: "Legal cost savings", value: "$50K+/yr" }, { label: "Contracts processed", value: "500+/mo" }],
    color: "slate",
    gradient: "from-slate-600 to-gray-700",
    enterprise: true,
  },
  {
    id: "content-ai",
    name: "Content Production AI",
    tagline: "Publish 10x more content, 10x faster",
    description: "Full-stack content engine — generates SEO blogs, social posts, email newsletters, ad copy, and video scripts all on-brand and on-schedule.",
    icon: "✍️",
    category: "Content",
    price: 147,
    priceNote: "/month",
    pricingModel: "monthly",
    rating: 4.5,
    reviews: 107,
    deployTime: "1 day",
    tags: ["Blog", "SEO", "Social", "Copywriting"],
    features: [
      "SEO-optimized long-form blog posts",
      "Brand voice matching & consistency",
      "Social media post generation",
      "Email newsletter creation",
      "Ad copy variations",
      "Video script writing",
      "Content calendar management",
      "WordPress/CMS auto-publishing",
    ],
    integrations: ["WordPress", "Webflow", "Buffer", "Mailchimp", "Ahrefs", "Semrush"],
    metrics: [{ label: "Content velocity", value: "10x faster" }, { label: "Organic traffic", value: "+156%" }, { label: "Content cost", value: "-80%" }],
    color: "rose",
    gradient: "from-rose-500 to-pink-600",
  },
  {
    id: "leadgen-ai",
    name: "Lead Generation AI",
    tagline: "Fill your pipeline while you focus on closing",
    description: "Identifies ideal prospects, finds contact details, qualifies them against your ICP, and delivers ready-to-contact leads daily.",
    icon: "🎯",
    category: "Sales",
    price: 347,
    priceNote: "/month",
    pricingModel: "monthly",
    rating: 4.8,
    reviews: 66,
    deployTime: "2 days",
    tags: ["Prospecting", "Lead Gen", "ICP", "Outbound"],
    features: [
      "ICP-based prospect identification",
      "Contact data enrichment",
      "LinkedIn & web scraping",
      "Intent signal monitoring",
      "Lead scoring & prioritization",
      "Daily lead delivery to CRM",
      "Lookalike audience building",
      "Competitor customer targeting",
    ],
    integrations: ["Apollo.io", "ZoomInfo", "Salesforce", "HubSpot", "LinkedIn Sales Nav", "Clay"],
    metrics: [{ label: "Qualified leads/month", value: "200+" }, { label: "Data accuracy", value: "95%" }, { label: "Time prospecting", value: "-95%" }],
    color: "violet",
    gradient: "from-violet-500 to-purple-600",
    new: true,
  },
];

export const categories = ["All", ...Array.from(new Set(agents.map(a => a.category)))];

export const colorMap: Record<string, { bg: string; text: string; border: string; light: string }> = {
  blue:   { bg: "bg-blue-500",   text: "text-blue-600",   border: "border-blue-200",   light: "bg-blue-50" },
  green:  { bg: "bg-green-500",  text: "text-green-600",  border: "border-green-200",  light: "bg-green-50" },
  purple: { bg: "bg-purple-500", text: "text-purple-600", border: "border-purple-200", light: "bg-purple-50" },
  orange: { bg: "bg-orange-500", text: "text-orange-600", border: "border-orange-200", light: "bg-orange-50" },
  indigo: { bg: "bg-indigo-500", text: "text-indigo-600", border: "border-indigo-200", light: "bg-indigo-50" },
  pink:   { bg: "bg-pink-500",   text: "text-pink-600",   border: "border-pink-200",   light: "bg-pink-50" },
  teal:   { bg: "bg-teal-500",   text: "text-teal-600",   border: "border-teal-200",   light: "bg-teal-50" },
  cyan:   { bg: "bg-cyan-500",   text: "text-cyan-600",   border: "border-cyan-200",   light: "bg-cyan-50" },
  yellow: { bg: "bg-yellow-500", text: "text-yellow-600", border: "border-yellow-200", light: "bg-yellow-50" },
  slate:  { bg: "bg-slate-600",  text: "text-slate-600",  border: "border-slate-200",  light: "bg-slate-50" },
  rose:   { bg: "bg-rose-500",   text: "text-rose-600",   border: "border-rose-200",   light: "bg-rose-50" },
  violet: { bg: "bg-violet-500", text: "text-violet-600", border: "border-violet-200", light: "bg-violet-50" },
};
