export interface Workflow {
  id: string;
  name: string;
  tagline: string;
  description: string;
  category: string;
  price: number;
  priceType: "one-time" | "monthly";
  setupTime: string;
  complexity: "Beginner" | "Intermediate" | "Advanced";
  icon: string;
  gradient: string;
  color: string;
  popular?: boolean;
  new?: boolean;
  bestseller?: boolean;
  tools: string[];        // Apps/tools it connects
  steps: string[];        // What the workflow does step-by-step
  deliverables: string[]; // What you get
  useCases: string[];
  metrics: { label: string; value: string }[];
  testimonial?: { quote: string; author: string; role: string };
}

export const workflows: Workflow[] = [
  // ─── MARKETING AUTOMATION ────────────────────────────────────────────────
  {
    id: "lead-nurture-email",
    name: "Lead Nurture Email Sequence",
    tagline: "Turn cold leads into paying customers on autopilot",
    description: "A 7-step email drip sequence that qualifies leads, delivers value, and books calls — fully automated from opt-in to conversion.",
    category: "Marketing",
    price: 297,
    priceType: "one-time",
    setupTime: "30 min",
    complexity: "Beginner",
    icon: "📧",
    gradient: "from-blue-500 to-cyan-500",
    color: "blue",
    popular: true,
    tools: ["Mailchimp", "ActiveCampaign", "HubSpot", "Klaviyo", "ConvertKit"],
    steps: [
      "Subscriber opts in via lead magnet or form",
      "AI segments contact by industry and intent",
      "7-email sequence delivers personalized value",
      "Engagement scoring tracks opens and clicks",
      "Hot leads auto-tagged and pushed to CRM",
      "Sales team notified when lead hits threshold"
    ],
    deliverables: ["7 pre-written email templates", "Automation flowchart", "Segmentation logic", "Lead scoring rules", "Setup guide (video + PDF)"],
    useCases: ["SaaS onboarding", "Coaching programs", "E-commerce welcome series", "B2B consultancy"],
    metrics: [{ label: "Avg Open Rate", value: "42%" }, { label: "Conversion Lift", value: "+38%" }, { label: "Hours Saved/mo", value: "20+" }],
    testimonial: { quote: "Set it up in an afternoon. Booked 4 calls in the first week.", author: "Sarah M.", role: "Founder, GrowthSaaS" },
  },
  {
    id: "social-content-pipeline",
    name: "Social Media Content Pipeline",
    tagline: "30 days of content generated, scheduled & posted — hands-free",
    description: "AI drafts, formats, and schedules a full month of platform-optimized posts across Instagram, LinkedIn, Twitter/X, and Facebook in one run.",
    category: "Marketing",
    price: 197,
    priceType: "one-time",
    setupTime: "45 min",
    complexity: "Beginner",
    icon: "📱",
    gradient: "from-pink-500 to-rose-500",
    color: "pink",
    bestseller: true,
    tools: ["Buffer", "Later", "Hootsuite", "Zapier", "Make (Integromat)", "Notion"],
    steps: [
      "Input brand voice, topics, and goals",
      "AI generates 30 posts with captions and hashtags",
      "Images auto-selected from Unsplash / brand assets",
      "Posts formatted per platform specs",
      "Scheduled in bulk to Buffer/Later",
      "Weekly performance report sent to email"
    ],
    deliverables: ["30-post content calendar", "Caption templates library", "Hashtag strategy per niche", "Canva template pack", "Automation blueprint"],
    useCases: ["Personal brands", "Small businesses", "Marketing agencies", "E-commerce stores"],
    metrics: [{ label: "Posts/Month", value: "30+" }, { label: "Time Saved", value: "12 hrs" }, { label: "Engagement Lift", value: "+55%" }],
    testimonial: { quote: "My Instagram went from 2% to 8% engagement within 6 weeks.", author: "James T.", role: "E-commerce Brand Owner" },
  },
  {
    id: "ad-campaign-launcher",
    name: "Paid Ad Campaign Launcher",
    tagline: "Launch profitable ad campaigns in under an hour",
    description: "Full ad campaign setup for Meta or Google Ads — audience research, copy variants, budget allocation, and A/B test structure all pre-built.",
    category: "Marketing",
    price: 347,
    priceType: "one-time",
    setupTime: "1 hr",
    complexity: "Intermediate",
    icon: "🎯",
    gradient: "from-orange-500 to-amber-500",
    color: "orange",
    new: true,
    tools: ["Meta Ads Manager", "Google Ads", "Zapier", "Google Sheets", "Slack"],
    steps: [
      "Input product, audience, and budget",
      "AI generates 5 ad copy variants per format",
      "Audience segments built from customer avatar",
      "Campaign structure (cold/warm/retargeting) configured",
      "A/B test rules set automatically",
      "Daily performance alerts sent to Slack"
    ],
    deliverables: ["Ad copy swipe file (15+ variants)", "Audience targeting sheet", "Campaign structure template", "Budget allocation calculator", "Reporting dashboard"],
    useCases: ["Product launches", "Lead generation", "E-commerce scaling", "Course promotions"],
    metrics: [{ label: "Setup Time", value: "< 1 hr" }, { label: "ROAS Avg", value: "3.8x" }, { label: "Copy Variants", value: "15+" }],
  },

  // ─── SALES & CRM ─────────────────────────────────────────────────────────
  {
    id: "crm-auto-update",
    name: "CRM Auto-Update & Deal Tracker",
    tagline: "Your CRM stays updated without lifting a finger",
    description: "Automatically logs emails, calls, and meetings to your CRM, updates deal stages based on activity, and alerts your team when deals go cold.",
    category: "Sales",
    price: 247,
    priceType: "one-time",
    setupTime: "45 min",
    complexity: "Intermediate",
    icon: "💼",
    gradient: "from-green-500 to-emerald-500",
    color: "green",
    popular: true,
    tools: ["Salesforce", "HubSpot CRM", "Pipedrive", "Gmail", "Outlook", "Slack", "Zapier"],
    steps: [
      "Connects to your email and calendar",
      "Every email/call auto-logged to correct deal",
      "AI extracts key info and updates deal fields",
      "Deal stage advances based on activity triggers",
      "Idle deals (7+ days) flag to sales manager",
      "Weekly pipeline summary sent to team"
    ],
    deliverables: ["Zapier/Make automation blueprint", "CRM field mapping guide", "Deal stage ruleset", "Slack alert templates", "Video walkthrough"],
    useCases: ["B2B sales teams", "Agencies", "Consultancies", "Real estate"],
    metrics: [{ label: "Data Entry Saved", value: "95%" }, { label: "Deal Visibility", value: "+70%" }, { label: "Close Rate Lift", value: "+22%" }],
    testimonial: { quote: "Our reps stopped dreading CRM updates. Data is always current now.", author: "Mike R.", role: "VP Sales, TechCorp" },
  },
  {
    id: "outbound-prospecting",
    name: "Outbound Prospecting Engine",
    tagline: "Find, enrich, and contact 100 ideal prospects per day",
    description: "Scrapes qualified leads from LinkedIn and web, enriches with contact data, personalizes outreach, and sends via email + LinkedIn — all automated.",
    category: "Sales",
    price: 397,
    priceType: "one-time",
    setupTime: "2 hrs",
    complexity: "Advanced",
    icon: "🔍",
    gradient: "from-violet-500 to-purple-600",
    color: "purple",
    bestseller: true,
    tools: ["Apollo.io", "LinkedIn Sales Nav", "Hunter.io", "Instantly.ai", "Clay", "Zapier"],
    steps: [
      "Define ICP (industry, company size, role, location)",
      "Automated scraping pulls matching prospects daily",
      "Contact data enriched (email, phone, LinkedIn)",
      "AI writes personalized first lines per prospect",
      "Multi-step outreach sequence triggered automatically",
      "Replies routed to inbox with context summary"
    ],
    deliverables: ["ICP definition template", "Automation blueprint (Make/Zapier)", "Email sequence copy (5 steps)", "LinkedIn message templates", "Prospect tracking sheet"],
    useCases: ["B2B SaaS", "Agencies", "Staffing firms", "Consultancies"],
    metrics: [{ label: "Prospects/Day", value: "100+" }, { label: "Reply Rate", value: "12-18%" }, { label: "Time Saved/Week", value: "15 hrs" }],
  },

  // ─── CUSTOMER SUPPORT ────────────────────────────────────────────────────
  {
    id: "support-ticket-ai",
    name: "AI Support Ticket Resolver",
    tagline: "Resolve 80% of support tickets without human intervention",
    description: "Triage, categorize, and auto-respond to support tickets using your knowledge base — escalates only the complex ones to your team.",
    category: "Customer Support",
    price: 297,
    priceType: "one-time",
    setupTime: "1 hr",
    complexity: "Intermediate",
    icon: "🎧",
    gradient: "from-teal-500 to-cyan-600",
    color: "teal",
    popular: true,
    tools: ["Zendesk", "Freshdesk", "Intercom", "Help Scout", "Slack", "Notion"],
    steps: [
      "Ticket arrives via email/chat/form",
      "AI categorizes by type and urgency",
      "Knowledge base searched for answer",
      "Personalized response drafted and sent",
      "Complex tickets escalated with context summary",
      "CSAT survey sent after resolution"
    ],
    deliverables: ["AI triage ruleset", "Response template library (50+)", "Escalation logic flowchart", "Knowledge base structure guide", "CSAT automation"],
    useCases: ["SaaS platforms", "E-commerce stores", "Service businesses", "Agencies"],
    metrics: [{ label: "Auto-Resolved", value: "80%" }, { label: "Response Time", value: "< 2 min" }, { label: "CSAT Score", value: "4.8/5" }],
    testimonial: { quote: "Went from 48-hour response times to under 5 minutes.", author: "Lisa K.", role: "Head of Support, Shopify Brand" },
  },

  // ─── HR & RECRUITING ─────────────────────────────────────────────────────
  {
    id: "recruiting-pipeline",
    name: "AI Recruiting Pipeline",
    tagline: "Hire faster — screen 200 applicants in the time it takes to read 10",
    description: "Automates job posting, applicant screening, scoring, interview scheduling, and follow-up communication end-to-end.",
    category: "HR & Recruiting",
    price: 347,
    priceType: "one-time",
    setupTime: "1.5 hrs",
    complexity: "Intermediate",
    icon: "👥",
    gradient: "from-indigo-500 to-blue-600",
    color: "indigo",
    new: true,
    tools: ["Greenhouse", "Lever", "Workable", "Calendly", "Gmail", "Slack", "Airtable"],
    steps: [
      "Job description auto-posted to 10+ job boards",
      "Applications collected into central dashboard",
      "AI scores each applicant against role criteria",
      "Top candidates auto-invited to schedule interview",
      "Interview reminders and prep materials sent",
      "Rejection emails sent to non-qualified candidates"
    ],
    deliverables: ["Job posting templates", "Scoring rubric (customizable)", "Interview question bank", "Email sequence templates", "Airtable tracking board"],
    useCases: ["Startups scaling fast", "HR teams", "Agencies", "SMBs without dedicated HR"],
    metrics: [{ label: "Screening Time", value: "-85%" }, { label: "Time to Hire", value: "-40%" }, { label: "Applicants Handled", value: "200+/run" }],
  },
  {
    id: "employee-onboarding",
    name: "Employee Onboarding Automation",
    tagline: "New hires go from offer to productive in 48 hours",
    description: "Triggers a full onboarding sequence: accounts created, documents sent, training assigned, intro meetings booked — all before day one.",
    category: "HR & Recruiting",
    price: 227,
    priceType: "one-time",
    setupTime: "1 hr",
    complexity: "Beginner",
    icon: "🤝",
    gradient: "from-emerald-500 to-teal-500",
    color: "emerald",
    tools: ["BambooHR", "Rippling", "DocuSign", "Slack", "Notion", "Google Workspace", "Zapier"],
    steps: [
      "Offer letter signed triggers automation",
      "IT accounts provisioned automatically",
      "Welcome email + first-week agenda sent",
      "Onboarding docs routed for e-signature",
      "30-60-90 day plan shared in Notion",
      "Buddy/mentor intro meeting auto-scheduled"
    ],
    deliverables: ["Onboarding checklist template", "Welcome email sequence", "30-60-90 day plan template", "Automation blueprint", "IT provisioning guide"],
    useCases: ["Remote teams", "Fast-growing startups", "SMBs", "Agencies with contractors"],
    metrics: [{ label: "Onboarding Time", value: "-60%" }, { label: "First-Week Satisfaction", value: "94%" }, { label: "HR Hours Saved", value: "8/hire" }],
  },

  // ─── E-COMMERCE ──────────────────────────────────────────────────────────
  {
    id: "abandoned-cart-recovery",
    name: "Abandoned Cart Recovery Engine",
    tagline: "Recover 15-25% of abandoned carts on autopilot",
    description: "Multi-channel recovery sequence using email, SMS, and retargeting ads — triggered the moment a cart is abandoned with smart timing and personalization.",
    category: "E-Commerce",
    price: 247,
    priceType: "one-time",
    setupTime: "45 min",
    complexity: "Beginner",
    icon: "🛒",
    gradient: "from-orange-400 to-red-500",
    color: "red",
    bestseller: true,
    tools: ["Shopify", "WooCommerce", "Klaviyo", "Postscript", "Meta Ads", "Zapier"],
    steps: [
      "Cart abandoned — trigger fires after 15 min",
      "Email 1: gentle reminder with cart preview",
      "SMS sent after 1 hour (if opted in)",
      "Email 2: social proof + urgency at 24 hrs",
      "Retargeting ad pixel fires on Facebook/Instagram",
      "Email 3: final discount offer at 48 hrs"
    ],
    deliverables: ["3-email recovery sequence", "SMS templates", "Retargeting ad copy", "Discount logic rules", "Klaviyo flow blueprint"],
    useCases: ["Shopify stores", "WooCommerce", "DTC brands", "Subscription boxes"],
    metrics: [{ label: "Recovery Rate", value: "15-25%" }, { label: "Revenue Recovered", value: "+$8K avg/mo" }, { label: "Setup Time", value: "< 1 hr" }],
    testimonial: { quote: "Added $12K/month in recovered revenue in the first 30 days.", author: "Emily W.", role: "DTC Brand Owner" },
  },
  {
    id: "product-review-machine",
    name: "Post-Purchase Review Machine",
    tagline: "Flood your store with 5-star reviews automatically",
    description: "Perfectly timed post-purchase sequence that drives reviews on Google, Trustpilot, and your store — filters unhappy customers before they post publicly.",
    category: "E-Commerce",
    price: 147,
    priceType: "one-time",
    setupTime: "30 min",
    complexity: "Beginner",
    icon: "⭐",
    gradient: "from-yellow-400 to-orange-500",
    color: "yellow",
    popular: true,
    tools: ["Shopify", "Klaviyo", "Yotpo", "Trustpilot", "Google Business", "Zapier"],
    steps: [
      "Order delivered — trigger fires automatically",
      "Satisfaction check email sent at day 3",
      "Happy customers directed to review platforms",
      "Neutral/unhappy routed to private feedback form",
      "Review submitted → discount coupon sent as thanks",
      "Low ratings alert sent to customer success team"
    ],
    deliverables: ["Email sequence templates", "Satisfaction gate logic", "Review platform links setup guide", "Coupon automation rules", "Monthly review report dashboard"],
    useCases: ["Shopify / WooCommerce", "Local businesses", "Service businesses", "Apps & SaaS"],
    metrics: [{ label: "Review Volume", value: "+340%" }, { label: "Avg Rating", value: "4.8★" }, { label: "Negative Posts", value: "-90%" }],
  },

  // ─── FINANCE & ACCOUNTING ─────────────────────────────────────────────────
  {
    id: "invoice-payment-followup",
    name: "Invoice & Payment Follow-Up System",
    tagline: "Get paid faster — no more awkward payment chasing",
    description: "Automated invoice reminders, payment tracking, and escalation sequence that reduces DSO by 40% without damaging client relationships.",
    category: "Finance",
    price: 197,
    priceType: "one-time",
    setupTime: "30 min",
    complexity: "Beginner",
    icon: "💰",
    gradient: "from-green-400 to-emerald-600",
    color: "green",
    tools: ["QuickBooks", "Xero", "FreshBooks", "Stripe", "Gmail", "Slack", "Zapier"],
    steps: [
      "Invoice sent — automation starts tracking",
      "Friendly reminder at 3 days before due date",
      "Due date reminder on the day",
      "Overdue notice at day 3 with payment link",
      "Escalation email at day 7 — CC owner",
      "Slack alert to finance team at day 14"
    ],
    deliverables: ["5-email reminder sequence", "Escalation logic flowchart", "Payment link integration guide", "Overdue tracking dashboard", "Client-friendly copy templates"],
    useCases: ["Freelancers", "Agencies", "Consultancies", "Small businesses"],
    metrics: [{ label: "DSO Reduction", value: "-40%" }, { label: "Late Invoices", value: "-65%" }, { label: "Time Saved/Month", value: "6 hrs" }],
  },
  {
    id: "expense-report-automation",
    name: "Expense Report Automation",
    tagline: "Receipt to approved expense report in 60 seconds",
    description: "Team members photo receipts, AI extracts data, auto-categorizes expenses, builds report, and routes for approval — no spreadsheets ever.",
    category: "Finance",
    price: 227,
    priceType: "one-time",
    setupTime: "1 hr",
    complexity: "Intermediate",
    icon: "🧾",
    gradient: "from-blue-400 to-indigo-600",
    color: "indigo",
    new: true,
    tools: ["Expensify", "Ramp", "QuickBooks", "Slack", "Google Drive", "Zapier", "Make"],
    steps: [
      "Employee photos receipt via mobile",
      "OCR extracts amount, vendor, date automatically",
      "AI categorizes expense against chart of accounts",
      "Report auto-compiled at end of each week",
      "Manager approval request sent via Slack/email",
      "Approved → synced to accounting software instantly"
    ],
    deliverables: ["Receipt capture workflow", "Categorization ruleset", "Approval routing logic", "Monthly report template", "Integration setup guides"],
    useCases: ["Teams with field staff", "Agencies", "Consulting firms", "Remote teams"],
    metrics: [{ label: "Processing Time", value: "-90%" }, { label: "Errors Eliminated", value: "98%" }, { label: "Approval Speed", value: "< 24 hrs" }],
  },

  // ─── OPERATIONS ──────────────────────────────────────────────────────────
  {
    id: "project-status-reporting",
    name: "Automated Project Status Reports",
    tagline: "Clients and stakeholders stay informed — without status meetings",
    description: "Pulls live data from your project tools and sends polished, branded weekly status reports to clients and leadership automatically.",
    category: "Operations",
    price: 197,
    priceType: "one-time",
    setupTime: "45 min",
    complexity: "Beginner",
    icon: "📊",
    gradient: "from-slate-500 to-gray-700",
    color: "slate",
    tools: ["Asana", "Monday.com", "ClickUp", "Jira", "Notion", "Slack", "Gmail"],
    steps: [
      "Every Friday at 4 PM automation triggers",
      "Task completion, blockers, milestones pulled from PM tool",
      "AI writes natural-language summary from raw data",
      "Branded report formatted with your logo/colors",
      "PDF generated and emailed to client list",
      "Internal Slack summary posted to team channel"
    ],
    deliverables: ["Report email template", "Data extraction blueprint", "PDF generation setup", "Client portal integration guide", "Scheduling configuration"],
    useCases: ["Agencies", "Consultancies", "Dev teams", "Project managers"],
    metrics: [{ label: "Meeting Time Saved", value: "3 hrs/week" }, { label: "Client Satisfaction", value: "+28%" }, { label: "Reporting Accuracy", value: "99%" }],
    testimonial: { quote: "Clients love the Friday reports. Saved us our weekly status call.", author: "David P.", role: "Agency Director" },
  },
  {
    id: "meeting-followup-action",
    name: "Meeting Notes & Action Item Tracker",
    tagline: "Every meeting ends with a clear action plan — automatically",
    description: "Records, transcribes, and summarizes meetings, then distributes action items to owners in your project management tool and follows up on completion.",
    category: "Operations",
    price: 247,
    priceType: "one-time",
    setupTime: "1 hr",
    complexity: "Intermediate",
    icon: "📝",
    gradient: "from-purple-500 to-violet-600",
    color: "purple",
    popular: true,
    tools: ["Zoom", "Google Meet", "Fireflies.ai", "Otter.ai", "Notion", "Asana", "Slack"],
    steps: [
      "Meeting recorded and auto-transcribed",
      "AI extracts decisions, action items, and owners",
      "Summary email sent to all attendees within 5 min",
      "Action items created in Asana/ClickUp with due dates",
      "Slack DMs sent to each task owner",
      "7-day follow-up sent if tasks remain incomplete"
    ],
    deliverables: ["Meeting bot setup guide", "Action item extraction prompt", "Task creation automation", "Follow-up sequence templates", "Summary email template"],
    useCases: ["Remote teams", "Client meetings", "Leadership teams", "Agencies"],
    metrics: [{ label: "Follow-Through Rate", value: "+65%" }, { label: "Time on Meeting Admin", value: "-80%" }, { label: "Action Items Missed", value: "Near zero" }],
  },

  // ─── LEGAL & COMPLIANCE ──────────────────────────────────────────────────
  {
    id: "contract-review-workflow",
    name: "Contract Review & Risk Alert",
    tagline: "Review contracts in minutes, not days — flag every risk automatically",
    description: "Upload any contract; AI extracts key clauses, flags non-standard terms, identifies risks, and produces a one-page summary with recommended actions.",
    category: "Legal",
    price: 447,
    priceType: "one-time",
    setupTime: "2 hrs",
    complexity: "Advanced",
    icon: "📋",
    gradient: "from-red-500 to-rose-600",
    color: "red",
    tools: ["DocuSign", "Google Drive", "Notion", "Slack", "Gmail", "Make (Integromat)"],
    steps: [
      "Contract uploaded to shared Drive/Dropbox folder",
      "AI parses all clauses and extracts key terms",
      "Risk flags identified (liability, IP, payment, termination)",
      "One-page summary generated with risk score (1-10)",
      "Lawyer review only required for high-risk items",
      "Approved contracts routed to DocuSign automatically"
    ],
    deliverables: ["Contract analysis prompt library", "Risk flag taxonomy (50+ clause types)", "Review workflow blueprint", "DocuSign routing automation", "Notion tracking dashboard"],
    useCases: ["Startups", "Agencies", "Consultancies", "SMBs without in-house legal"],
    metrics: [{ label: "Review Time", value: "-75%" }, { label: "Risks Caught", value: "95%+" }, { label: "Legal Costs Saved", value: "$2K+/contract" }],
  },

  // ─── CONTENT & SOCIAL ─────────────────────────────────────────────────────
  {
    id: "content-repurposing-engine",
    name: "Content Repurposing Engine",
    tagline: "One piece of content → 10 assets across every platform",
    description: "Turn a blog post, podcast, or YouTube video into LinkedIn posts, Twitter threads, Instagram captions, email newsletters, and short-form clips — automatically.",
    category: "Content",
    price: 197,
    priceType: "one-time",
    setupTime: "1 hr",
    complexity: "Beginner",
    icon: "♻️",
    gradient: "from-fuchsia-500 to-pink-600",
    color: "fuchsia",
    bestseller: true,
    tools: ["Notion", "Zapier", "Buffer", "Descript", "ChatGPT API", "Google Docs", "Airtable"],
    steps: [
      "Paste blog URL or upload transcript",
      "AI extracts key insights and quotes",
      "Formats content for each platform (LinkedIn, Twitter, IG, email)",
      "10 platform-native assets generated in 60 seconds",
      "Auto-scheduled across channels via Buffer/Later",
      "Performance data fed back to refine future content"
    ],
    deliverables: ["Platform formatting templates", "Content extraction prompt library", "Scheduling automation blueprint", "Airtable content tracker", "Brand voice guide template"],
    useCases: ["Content creators", "B2B marketers", "Coaches/consultants", "Podcasters"],
    metrics: [{ label: "Content Output", value: "10x" }, { label: "Production Time", value: "-85%" }, { label: "Platform Reach", value: "5+ channels" }],
    testimonial: { quote: "I write one article a week and it fills my entire social calendar.", author: "Nina C.", role: "B2B Marketing Consultant" },
  },
];

export const workflowCategories = [
  { id: "all", label: "All Workflows", icon: "🔥" },
  { id: "Marketing", label: "Marketing", icon: "📣" },
  { id: "Sales", label: "Sales", icon: "💼" },
  { id: "Customer Support", label: "Customer Support", icon: "🎧" },
  { id: "HR & Recruiting", label: "HR & Recruiting", icon: "👥" },
  { id: "E-Commerce", label: "E-Commerce", icon: "🛒" },
  { id: "Finance", label: "Finance", icon: "💰" },
  { id: "Operations", label: "Operations", icon: "⚙️" },
  { id: "Legal", label: "Legal", icon: "📋" },
  { id: "Content", label: "Content", icon: "✏️" },
];

export const colorMap: Record<string, { bg: string; text: string; border: string; light: string }> = {
  blue:    { bg: "bg-blue-600",    text: "text-blue-600",    border: "border-blue-200",    light: "bg-blue-50"    },
  pink:    { bg: "bg-pink-500",    text: "text-pink-600",    border: "border-pink-200",    light: "bg-pink-50"    },
  orange:  { bg: "bg-orange-500",  text: "text-orange-600",  border: "border-orange-200",  light: "bg-orange-50"  },
  green:   { bg: "bg-green-600",   text: "text-green-600",   border: "border-green-200",   light: "bg-green-50"   },
  purple:  { bg: "bg-purple-600",  text: "text-purple-600",  border: "border-purple-200",  light: "bg-purple-50"  },
  teal:    { bg: "bg-teal-600",    text: "text-teal-600",    border: "border-teal-200",    light: "bg-teal-50"    },
  indigo:  { bg: "bg-indigo-600",  text: "text-indigo-600",  border: "border-indigo-200",  light: "bg-indigo-50"  },
  red:     { bg: "bg-red-600",     text: "text-red-600",     border: "border-red-200",     light: "bg-red-50"     },
  yellow:  { bg: "bg-yellow-500",  text: "text-yellow-600",  border: "border-yellow-200",  light: "bg-yellow-50"  },
  slate:   { bg: "bg-slate-700",   text: "text-slate-700",   border: "border-slate-200",   light: "bg-slate-50"   },
  emerald: { bg: "bg-emerald-600", text: "text-emerald-600", border: "border-emerald-200", light: "bg-emerald-50" },
  fuchsia: { bg: "bg-fuchsia-600", text: "text-fuchsia-600", border: "border-fuchsia-200", light: "bg-fuchsia-50" },
};
